# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "entries", :force => true do |t|
    t.column "title",      :string,   :null => false
    t.column "body",       :text,     :null => false
    t.column "tag_id",     :integer
    t.column "user_id",    :integer,  :null => false
    t.column "comment_id", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "entries", ["user_id"], :name => "fk_entry_users"
  add_index "entries", ["tag_id"], :name => "fk_entry_tags"

  create_table "permissions", :force => true do |t|
    t.column "permission_id",   :integer, :null => false
    t.column "permission_name", :string,  :null => false
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "tags", :force => true do |t|
    t.column "tag_id",   :integer, :null => false
    t.column "tag_name", :text,    :null => false
  end

  create_table "users", :force => true do |t|
    t.column "name",            :string,   :null => false
    t.column "permission_id",   :integer,  :null => false
    t.column "profile",         :text
    t.column "hashed_password", :string
    t.column "salt",            :string
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
  end

end
